name: sesoft_uni_mobile
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  go_router: ^10.0.0
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  flutter_riverpod: ^2.4.0
  riverpod_annotation: ^2.1.5
  dio: ^5.3.2
  flex_color_scheme: ^7.3.1
  flutter_secure_storage: ^9.0.0
  skeletonizer: ^0.7.0
  shared_preferences: ^2.2.1
  easy_debounce: ^2.0.3
  image_picker: ^1.0.4
  permission_handler: ^11.1.0
  open_file: ^3.3.2
  path_provider: ^2.1.1
  http: ^1.1.0
  share_plus: ^7.2.1
  socket_io_client: ^2.0.3+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  freezed: ^2.4.2
  json_serializable: ^6.7.1
  riverpod_generator: ^2.3.2
  custom_lint: ^0.5.3
  riverpod_lint: ^2.0.4
  flutter_launcher_icons: "^0.13.1"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
